In [1]:
import torch 

In [2]:
x = torch.zeros(3,3)

In [3]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
x = torch.rand(4,3)

In [5]:
print(x)

tensor([[0.8986, 0.7915, 0.9712],
        [0.7333, 0.3531, 0.7527],
        [0.5465, 0.8581, 0.1193],
        [0.2502, 0.2099, 0.9013]])


In [6]:
x.size()

torch.Size([4, 3])

In [7]:
z = x.numpy()

In [8]:
z

array([[0.8985674 , 0.79151416, 0.9712245 ],
       [0.7332925 , 0.3530724 , 0.75268084],
       [0.54653794, 0.85810655, 0.11932105],
       [0.25024772, 0.20986623, 0.9013399 ]], dtype=float32)